s = 'My name is Mike. HI Mike'
print(s)
is_start = s.startswith("My")
print(is_start)

is_start = s.startswith("is")
print(is_start)
print(s.find("Mike"))
print(s.rfind("Mike"))
print(s.count("Mike"))
print(s.capitalize())
print(s.title())
print(s.upper())
print(s.lower())
print(s.replace("Mike", "Nancy"))
